tracker_type: botsort
track_high_thresh: 0.3
track_low_thresh: 0.1
new_track_thresh: 0.4
match_thresh: 0.5
track_buffer: 30
fuse_score: true
gmc_method: none
with_reid: true
proximity_thresh: 0.2
appearance_thresh: 0.4
model: auto


