tracker_type: botsort # (str) Tracker backend: botsort|bytetrack; choose botsort to enable BoT-SORT features
track_high_thresh: 0.2 # slightly lower to reduce missed associations
track_low_thresh: 0.1 # keep default low threshold similar to legacy
new_track_thresh: 0.3 # align with legacy ByteTrack new track threshold
track_buffer: 50 # align with legacy ByteTrack buffer
match_thresh: 0.4 # lower to make matching less strict, reduce ID breaks
fuse_score: true # (bool) Fuse detection score with motion/IoU for matching; stabilizes weak detections

# BoT-SORT specifics
gmc_method: none # (str) Global motion compensation: sparseOptFlow|orb|none; helps moving camera scenes

# ReID model related thresh
proximity_thresh: 0.2 # (float) Min IoU to consider tracks proximate for ReID; higher is stricter
appearance_thresh: 0.3 # (float) Min appearance similarity for ReID; raise to avoid identity swaps
with_reid: true # (bool) Enable ReID model use; needs extra model and compute
model: auto # (str) ReID model name/path; "auto" uses detector features if available


