tracker_type: botsort
track_high_thresh: 0.25
track_low_thresh: 0.05
new_track_thresh: 0.25
match_thresh: 0.4
track_buffer: 90
fuse_score: true
gmc_method: none
with_reid: false
proximity_thresh: 0.5
appearance_thresh: 0.5
model: auto


