tracker_type: botsort # use with our internal tracker flow; ignored by Ultralytics YAML

# BoT-SORT parameters (only used when tracker_type == 'botsort')
track_high_thresh: 0.55    # Higher: cleaner tracks but more misses; Lower: more tracks incl. false positives
track_low_thresh: 0.12     # Recovery threshold for low-score matches; Higher: stricter recovery; Lower: easier recovery
new_track_thresh: 0.55     # New track creation threshold; Higher: fewer new IDs; Lower: more new (risk of false) IDs
match_thresh: 0.75         # Association similarity threshold; Higher: stricter matching (fewer ID switches but more breaks)
track_buffer: 50           # Frames to keep lost tracks; Higher: bridges occlusions; too high may cause stale IDs
fuse_score: true           # Fuse detection score with motion/IoU; On stabilizes weak detections; Off relies on geometry
gmc_method: none           # Global motion compensation: sparseOptFlow|orb|none; use for moving cameras
with_reid: true            # Enable appearance ReID; On reduces switches with stable appearance; costly and view-dependent
proximity_thresh: 0.3      # Min IoU for proximity in ReID; Higher: stricter; Lower: more permissive
appearance_thresh: 0.75    # Min appearance similarity; Higher: fewer wrong merges; Lower: fewer ID breaks but more swaps
model: auto                # ReID model path/name; 'auto' lets tracker choose defaults


