tracker_type: botsort
model: auto
gmc_method: sparseOptFlow
fuse_score: True
# Common BoT-SORT params with safe defaults
track_high_thresh: 0.6
track_low_thresh: 0.1
new_track_thresh: 0.7
match_thresh: 0.8
track_buffer: 30
proximity_thresh: 0.5
appearance_thresh: 0.25


